version: '3'

services:
    windtrail:
        container_name: windtrail
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 8000:8000
            - 9000:9000
            - 3000:3000
        volumes:
            - ./volumes:/workspace/volumes
            - ./app:/workspace/app
        tty: true
        stdin_open: true